name: PPU Publish Staging

on:
  release:
    types: [created]
  push:

jobs:
  build-publish:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Tooling
        run: |
          SHOPIFY_CLI_URL="https://github.com/Shopify/shopify-app-cli/releases/download/v1.2.0/shopify-cli-1.2.0.deb"
          DOWNLOAD_PATH="/tmp/shopify-cli-1.2.0.deb"
          curl -L -o $DOWNLOAD_PATH  $SHOPIFY_CLI_URL
      - name: Run Build
        run: |
          ls /tmp
