name: PPU Publish Staging

on:
  release:
    types: [created]
  push:

jobs:
  build-publish:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Setup Tooling
        run: |
          SHOPIFY_CLI_URL="https://github.com/Shopify/shopify-app-cli/releases/download/v1.2.0/shopify-cli-1.2.0.deb"
          DOWNLOAD_PATH="/tmp/shopify-cli-1.2.0.deb"
          curl -L -o $DOWNLOAD_PATH  $SHOPIFY_CLI_URL
          sudo apt install $DOWNLOAD_PATH

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          cd post-purchase-extension
          echo "SHOPIFY_API_KEY=${{ secrets.SHOPIFY_API_KEY }}" >> .env
          echo "SHOPIFY_API_SECRET=${{ secrets.SHOPIFY_API_SECRET }}" >> .env
          echo "EXTENSION_TITLE=${{ secrets.EXTENSION_TITLE }}" >> .env
          echo "EXTENSION_OD=${{ secrets.EXTENSION_ID }}" >> .env

      - name: Run Build
        run: shopify build
